import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from '@/styles/Providers';
import 'bootstrap/dist/css/bootstrap.min.css';
import NavigationBar from '@/components/Navbar';
import { Roboto } from 'next/font/google';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import 'swiper/css/free-mode';
import Footer from '@/components/Footer';

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <NavigationBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
